### ISSUE TITLE
Kactus (0.2.8) does not regenerate Sketch file

### ISSUE THREAD

**Issue by VitalikL** [Adventech/design#1]
When I open Developer Tools I see this error

```
Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at doc.pages.pages.sort (/private/var/folders/l1/30c4239j33l6j3c9g_jbbdvh0000gn/T/AppTranslocation/A…/Resources/app/node_modules/kactus-cli/lib/import/importDocumentJSON.js:37:23)
    at Array.sort (native)
    at fs.readFile.then.then (/private/var/folders/l1/30c4239j33l6j3c9g_jbbdvh0000gn/T/AppTranslocation/A…/Resources/app/node_modules/kactus-cli/lib/import/importDocumentJSON.js:36:23)
    at <anonymous>
```

**Comment by hebertialmeida** [comment]
Try it now 😄
